#!/usr/bin/python

import os
import sys
import re

# compile with ROOT, Geant4, MySQL and BOOST
def compile(filename):
    ## ROOT part
    cflags = os.popen('root-config --cflags').readline().strip()
    ldflags = os.popen('root-config --ldflags --glibs').readline().strip()

    ## basic
    ldflags = ldflags + ' -L./ -lAnaUtil -Wl,--no-as-needed'
    if os.path.exists('kTracker/lib/libkTracker.so'):
        cflags = cflags + ' -IkTracker/inc ' + os.popen('geant4-config --cflags').readline().strip()
        ldflags = ldflags + ' -LkTracker/lib -lkTracker ' + os.popen('geant4-config --libs').readline().strip()

    ## data version
    cflags = cflags + ' -D' + dataset

    print cflags
    print ldflags

    os.system('g++ '+cflags+' -c '+filename+'.cxx')
    os.system('g++ -o '+filename+' '+filename+'.o '+ldflags)
    os.system('rm '+filename+'.o')

# make sure it exists
if not os.path.isfile(sys.argv[1].replace('.cxx', '')+'.cxx'):
    print 'File does not exist!'
    sys.exit(1)

# extract the path and source file name
args = re.split('/', sys.argv[1])
targetName = args[-1].replace('.cxx', '')
sourceName = targetName + '.cxx'
sourcePath = sys.argv[1].replace('.cxx', '').replace(targetName, '')

dataset = 'ALL'
if len(sys.argv) > 2:
    dataset = sys.argv[2].upper()

# copy the source file to KTRACKER_ROOT, compile an delete it afterwards
if len(args) == 1 or (len(args) == 2 and args[0] == '.'):
    compile(targetName)
elif os.path.isfile(sourceName):
    print 'File already exists in both KTRACKER_ROOT and '+sys.argv[1].replace(sourceName, '')+'!! Please check.'
else:
    os.system('cp '+sourcePath+'/'+sourceName+' '+sourceName)
    compile(targetName)
    os.system('rm '+sourceName)
